version: 1.0.{build}
build: off
test_script:
  - ps: >-

    git clone --quiet https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 themis

    git clone --quiet https://github.com/vim-jp/vital.vim.git vital


    $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'

    $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim'


    (New-Object Net.WebClient).DownloadFile('http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip', $zip)


    [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null

    [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)


    $Env:THEMIS_VIM = $vim + '\vim74-kaoriya-win64\vim.exe'


    & $Env:THEMIS_VIM --version

    .\themis\bin\themis.bat -r --runtimepath vital --reporter spec
